export const REDIS_CONNECTION = 'REDIS_CONNECTION';

export const LOGGER = 'LOGGER';
export const ERROR_HANDLER = 'ERROR_HANDLER';

export const MASTER_REPORT_SERVICE = 'MASTER_REPORT_SERVICE';
export const MASTER_REPORT_REPO = 'MASTER_REPORT_REPO';
